name: DockerHubDemo

on:
  [push, pull_request, workflow_dispatch]
  
  # push:
  #   branches: [ "main" ]

jobs:
  
  build:
  
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0

      - name: install node dependencies for testing
        run: npm install

      - name: run node tests to audit codebase
        run: npm test

  build_docker_image:
    name: build docker image for image repository
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        
      - name: install runtime dependencies only
        run: npm i --omit=dev
        
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_TOKEN }}
          
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: build the push to docker hub
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.HUB_USERNAME }}/external:hub.${{ github.run_number }}










